### ISSUE TITLE
The API For the Map

### ISSUE THREAD

**Issue by iJustWannShareCode** [itsawednesday/UniChat#1]
Hello,

I am hoping that you are one of the members who were in our group in second year and took part in making this project. If that's the case, can you please edit the API key for the map please? Google just sent me an email as I got that key as non commercial/private and they're not happy that the key is available to public. I will also make sure that the key is deactivated and cannot be used in the future.

**Comment by itsawednesday** [comment]
Hey, absolutely but do you perhaps know where exactly I can locate it? I’m guessing it’s not this line in ProfileAcitivty?  @RequiresApi(api = Build.VERSION_CODES.LOLLIPOP_MR1)

**Comment by iJustWannShareCode** [comment]
https://github.com/itsawednesday/UniChat/blob/7430dbb5dfaa0608b5f4d49bedc243f160579b21/MapChatAndroid/app/src/main/res/values/map_api.xml it's here

**Comment by itsawednesday** [comment]
Thanks a lot, its fixed

**Comment by iJustWannShareCode** [comment]
No worries, and thank you for your quick response. If you wish you can delete this issue now.
